# Generated by Django 6.1.1 on 2026-09-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_learnerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='learneranalysis',
            name='entered_skills',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='learneranalysis',
            name='recommendations',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='learneranalysis',
            name='resume_text',
            field=models.TextField(blank=True),
        ),
    ]
