# Generated by Django 6.1.1 on 2026-09-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_learneranalysis_entered_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learneranalysis',
            name='experience_level',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='learneranalysis',
            name='learning_interest',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
